# $Id: Makefile,v 1.3 2002/03/09 16:18:18 dijkstra Exp $

LIB=	mon
SRCS=   error.c lex.c xmalloc.c net.c data.c

NOPROFILE= yes
NOPIC=	yes
DEBUG=-DDEBUG -g -Wall

.include <bsd.own.mk>
.include <bsd.lib.mk>
